version: '3.9'
services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skilltest
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    command: npm run dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: mysql://app:app@db:3306/skilltest
      JWT_SECRET: supersecret
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  db_data:
